const siteTranslations = {
    "en": {
        "nav_home": "Home",
        "nav_services": "Services",
        "nav_blog": "Blog",
        "nav_about": "About Us",
        "nav_contact": "Contact",
        "nav_projects": "Projects",
        "nav_faq": "FAQ",
        "menu_all_services": "All Services",
        "menu_social_media_marketing": "Social Media Marketing",
        "menu_web_design_development": "Web Design & Development",
        "menu_branding_graphics_design": "Branding & Graphics Design",
        "menu_printing_brand_production": "Printing & Brand Production",
        "header_call_anytime": "Call Anytime",
        "footer_copyright": "© Copyright 2026 by Anasi Marketing",
        "service_web_design": "Website Design (UI/UX)",
        "service_corp_web": "Corporate/Portfolio Websites",
        "service_maint": "Maintenance & Support",
        "service_branding": "Branding & Creative Design",
        "btn_get_started": "Get Started Free",
        "search_placeholder": "Search...",
        "about_title": "About Our Company",
        "about_heading": "We Deliver Innovative Ideas To Elevate Your Digital Agency.",
        "about_text": "We are a results-driven digital marketing and creative agency built for brands that value quality, clarity, and impact.",
        "services_title": "Our Services",
        "services_heading": "Empower Your Business With<br>Innovative Digital Services",
        "blog_heading": "Latest News & Articles",
        "banner_sub_title": "We Create Powerful Digital Experiences",
        "banner_title": "We don’t just market brands — we position them for long-term success.",
        "banner_text": "We are a premium full-service digital marketing and creative agency delivering strategy-led solutions that help brands grow, stand out, and lead in competitive markets.",
        "btn_custom_quote": "Request a Custom Quote",
        "banner_info_text": "Elevate Your Brand Today",
        "service_social_media": "Social<br>Media<br>Marketing",
        "service_sem": "Search Engine Marketing",
        "service_video_editing": "Video & Motion Graphics",
        "btn_more": "More",
        "about_exp_text": "Experience quality digital marketing services",
        "btn_discover_more": "DISCOVER MORE",
        "why_choose_us": "why choose us",
        "leading_company_title": "Recognized As One Of The Leading Company!",
        "contact_us_title": "Contact us",
        "get_in_touch_title": "Get in Touch",
        "form_name": "Your Name",
        "form_email": "Email Address",
        "form_subject": "Enter Subject",
        "form_phone": "Enter Phone",
        "form_message": "Write a Message",
        "btn_send_message": "Send A Message",
        "from_the_blog": "From The Blog",
        "news_articles_title": "News & articles",
        "read_more": "Read More",
        "footer_about_text": "We are a results-driven digital marketing and creative agency.",
        "footer_quick_link": "Quick Link",
        "footer_company": "Company",
        "footer_contact": "Contact",
        "how_it_works_title": "How it works",
        "how_it_works_heading": "Our Approach Is To Create",
        "how_it_works_step1": "Project Planning",
        "how_it_works_step2": "Development",
        "how_it_works_step3": "Quick Support",
        "footer_looking_for": "Looking For Professional Digital Marketing?",
        "service_item_1": "Website Maintenance & Updates",
        "service_item_2": "Performance Optimization",
        "service_item_3": "Security Monitoring",
        "service_item_4": "Backup & Recovery",
        "sm_strategy": "Strategy & Content",
        "sm_paid_ads": "Paid Advertising",
        "sm_community": "Community Growth",
        "sm_analytics": "Analytics",
        "sem_google_ads": "Google Ads",
        "sem_display_ads": "Display Advertising",
        "sem_retargeting": "Retargeting",
        "sem_keyword_research": "Keyword Research",
        "web_design_custom": "Custom Website Design",
        "web_design_ecommerce": "E-commerce Solutions",
        "web_design_seo": "SEO Optimization",
        "web_design_maintenance": "Maintenance",
        "branding_strategy": "Brand Strategy",
        "branding_logo": "Logo Design",
        "branding_identity": "Corporate Identity",
        "branding_creatives": "Marketing Creatives",
        "video_promotional": "Promotional Videos",
        "video_reels": "Social Media Reels",
        "video_motion": "Motion Graphics",
        "video_animations": "Logo Animations",
        "call_anytime_label": "Call Anytime",
        "video_editing_menu": "Video Editing & Motion Graphics",
        "blog_by": "By",
        "blog_no_comments": "No Comments",
        "blog_latest_news": "Latest News",
        "blog_cat_ai_content": "AI Content",
        "blog_cat_ai_tech": "AI Technology",
        "blog_cat_ui_design": "UI Design",
        "footer_web_design": "Web Design",
        "contact_send_email": "Send Email",
        "contact_location": "Nairobi, Kenya",
        "blog_title_web_dev": "Web Development Essentials Every Business",
        "blog_title_ai_web": "How AI is Revolutionizing Web Development",
        "blog_title_hashtag": "Effective Hashtag Strategies to Increase Reach"
    },
    "sw": {
        "nav_home": "Nyumbani",
        "nav_services": "Huduma",
        "nav_blog": "Blogu",
        "nav_about": "Kuhusu Sisi",
        "nav_contact": "Wasiliana Nasi",
        "nav_projects": "Miradi",
        "nav_faq": "Maswali ya Mara kwa Mara",
        "menu_all_services": "Huduma Zote",
        "menu_social_media_marketing": "Uuzaji wa Mitandao ya Kijamii",
        "menu_web_design_development": "Ubunifu na Uendelezaji wa Tovuti",
        "menu_branding_graphics_design": "Ubunifu wa Chapa na Michoro",
        "menu_printing_brand_production": "Uchapishaji na Uzalishaji wa Chapa",
        "header_call_anytime": "Piga Simu Wakati Wowote",
        "footer_copyright": "© Hakimiliki 2026 na Anasi Marketing",
        "service_web_design": "Ubunifu wa Tovuti (UI/UX)",
        "service_corp_web": "Tovuti za Kampuni/Portfolio",
        "service_maint": "Ukarabati na Msaada",
        "service_branding": "Ubunifu wa Chapa",
        "btn_get_started": "Anza Bure",
        "search_placeholder": "Tafuta...",
        "about_title": "Kuhusu Kampuni Yetu",
        "about_heading": "Tunatoa Mawazo Bunifu Ili Kuinua Wakala Wako wa Kidijitali.",
        "about_text": "Sisi ni wakala wa uuzaji wa kidijitali na ubunifu unaoendeshwa na matokeo.",
        "services_title": "Huduma Zetu",
        "services_heading": "Wezesha Biashara Yako na<br>Huduma Bunifu za Kidijitali",
        "blog_heading": "Habari za Hivi Punde na Makala",
        "banner_sub_title": "Tunaunda Uzoefu Wenye Nguvu wa Kidijitali",
        "banner_title": "Hatuuzi tu chapa — tunaziweka kwa mafanikio ya muda mrefu.",
        "banner_text": "Sisi ni wakala wa hali ya juu wa uuzaji wa kidijitali na ubunifu.",
        "btn_custom_quote": "Omba Nukuu Maalum",
        "banner_info_text": "Inua Chapa Yako Leo",
        "service_social_media": "Uuzaji wa<br>Mitandao ya<br>Kijamii",
        "service_sem": "Uuzaji wa Injini ya Utafutaji",
        "service_video_editing": "Uhariri wa Video na Michoro",
        "btn_more": "Zaidi",
        "about_exp_text": "Pata huduma bora za uuzaji wa kidijitali",
        "btn_discover_more": "GUNDUA ZAIDI",
        "why_choose_us": "kwa nini utuchague",
        "leading_company_title": "Inatambulika Kama Moja ya Kampuni Inayoongoza!",
        "contact_us_title": "Wasiliana nasi",
        "get_in_touch_title": "Wasiliana Nasi",
        "form_name": "Jina Lako",
        "form_email": "Anwani ya Barua Pepe",
        "form_subject": "Ingiza Somo",
        "form_phone": "Ingiza Simu",
        "form_message": "Andika Ujumbe",
        "btn_send_message": "Tuma Ujumbe",
        "from_the_blog": "Kutoka kwa Blogu",
        "news_articles_title": "Habari na makala",
        "read_more": "Soma Zaidi",
        "footer_about_text": "Sisi ni wakala wa uuzaji wa kidijitali na ubunifu unaoendeshwa na matokeo.",
        "footer_quick_link": "Kiungo cha Haraka",
        "footer_company": "Kampuni",
        "footer_contact": "Wasiliana",
        "how_it_works_title": "Jinsi inavyofanya kazi",
        "how_it_works_heading": "Mbinu Yetu Ni Kuunda",
        "how_it_works_step1": "Upangaji wa Mradi",
        "how_it_works_step2": "Maendeleo",
        "how_it_works_step3": "Msaada wa Haraka",
        "footer_looking_for": "Unatafuta Huduma za Kitaalamu za Uuzaji?",
        "service_item_1": "Ukarabati wa Tovuti na Masasisho",
        "service_item_2": "Uboreshaji wa Utendaji",
        "service_item_3": "Ufuatiliaji wa Usalama",
        "service_item_4": "Hifadhi na Urejeshaji",
        "sm_strategy": "Mkakati & Maudhui",
        "sm_paid_ads": "Matangazo Yaliyolipiwa",
        "sm_community": "Ukuaji wa Jamii",
        "sm_analytics": "Uchambuzi",
        "sem_google_ads": "Google Ads",
        "sem_display_ads": "Matangazo ya Onyesho",
        "sem_retargeting": "Kurejea Lengo",
        "sem_keyword_research": "Utafiti wa Neno Muhimu",
        "web_design_custom": "Ubunifu wa Tovuti Maalum",
        "web_design_ecommerce": "Suluhu za E-commerce",
        "web_design_seo": "Uboreshaji wa SEO",
        "web_design_maintenance": "Ukarabati",
        "branding_strategy": "Mkakati wa Chapa",
        "branding_logo": "Ubunifu wa Nembo",
        "branding_identity": "Kitambulisho cha Kampuni",
        "branding_creatives": "Ubunifu wa Uuzaji",
        "video_promotional": "Video za Kumwaliko",
        "video_reels": "Vilunde vya Mitandao ya Kijamii",
        "video_motion": "Michoro",
        "video_animations": "Uhuishaji wa Nembo",
        "call_anytime_label": "Piga Simu Wakati Wowote",
        "video_editing_menu": "Uhariri wa Video na Michoro",
        "blog_by": "Na",
        "blog_no_comments": "Hakuna Maoni",
        "blog_latest_news": "Habari za Hivi Punde",
        "blog_cat_ai_content": "Maudhui ya AI",
        "blog_cat_ai_tech": "Teknolohia ya AI",
        "blog_cat_ui_design": "Muundo wa UI",
        "footer_web_design": "Ubunifu wa Tovuti",
        "contact_send_email": "Tuma Barua Pepe",
        "contact_location": "Nairobi, Kenya",
        "blog_title_web_dev": "Misingi ya Uendelezaji wa Tovuti kwa Kila Biashara",
        "blog_title_ai_web": "Jinsi AI Inavyobadilisha Uendelezaji wa Tovuti",
        "blog_title_hashtag": "Mikakati Bora ya Hashtag Kuongeza Ufikiaji"
    },
    "fr": {
        "nav_home": "Accueil",
        "nav_services": "Services",
        "nav_blog": "Blog",
        "nav_about": "À Propos",
        "nav_contact": "Contact",
        "nav_projects": "Projets",
        "nav_faq": "FAQ",
        "menu_all_services": "Tous les services",
        "menu_social_media_marketing": "Marketing des médias sociaux",
        "menu_web_design_development": "Conception et développement Web",
        "menu_branding_graphics_design": "Branding et design graphique",
        "menu_printing_brand_production": "Impression et production de marque",
        "header_call_anytime": "Appelez à tout moment",
        "footer_copyright": "© Droit d'auteur 2026 par Anasi Marketing",
        "service_web_design": "Conception de sites Web (UI/UX)",
        "service_corp_web": "Sites Web d'entreprise/Portfolio",
        "service_maint": "Entretien et assistance",
        "service_branding": "Branding et design créatif",
        "btn_get_started": "Commencez gratuitement",
        "search_placeholder": "Recherche...",
        "about_title": "À Propos de Notre Entreprise",
        "about_heading": "Nous Livrons des Idées Innovantes Pour Élever Votre Agence Digitale.",
        "about_text": "Nous sommes une agence de marketing digital et de création axée sur les résultats.",
        "services_title": "Nos Services",
        "services_heading": "Donnez de l'Énergie à Votre Entreprise Avec<br>des Services Digitaux Innovants",
        "blog_heading": "Dernières Nouvelles et Articles",
        "banner_sub_title": "Nous Créons des Expériences Digitales Puissantes",
        "banner_title": "Nous ne nous contentons pas de commercialiser des marques — nous les positionnons.",
        "banner_text": "Nous sommes une agence de marketing digital et de création de premier plan.",
        "btn_custom_quote": "Demander un devis personnalisé",
        "banner_info_text": "Élevez votre marque aujourd'hui",
        "service_social_media": "Marketing des<br>médias<br>sociaux",
        "service_sem": "Marketing par moteur de recherche",
        "service_video_editing": "Montage vidéo et graphisme animé",
        "btn_more": "Plus",
        "about_exp_text": "Plus de 50 services d'expérience",
        "btn_discover_more": "DÉCOUVRIR PLUS",
        "why_choose_us": "Pourquoi nous choisir",
        "leading_company_title": "Reconnue comme l'une des entreprises leaders !",
        "contact_us_title": "Contactez-nous",
        "get_in_touch_title": "Entrer en contact",
        "form_name": "Votre nom",
        "form_email": "Adresse e-mail",
        "form_subject": "Entrez l'objet",
        "form_phone": "Entrez le téléphone",
        "form_message": "Écrire un message",
        "btn_send_message": "Envoyer un message",
        "from_the_blog": "Du blog",
        "news_articles_title": "Nouvelles et articles",
        "read_more": "Lire la suite",
        "footer_about_text": "Nous sommes une agence de marketing digital et de création axée sur les résultats.",
        "footer_quick_link": "Lien rapide",
        "footer_company": "Entreprise",
        "footer_contact": "Contact",
        "how_it_works_title": "Comment ça marche",
        "how_it_works_heading": "Notre approche consiste à créer",
        "how_it_works_step1": "Planification du projet",
        "how_it_works_step2": "Développement",
        "how_it_works_step3": "Assistance rapide",
        "footer_looking_for": "Vous recherchez un marketing digital professionnel ?",
        "service_item_1": "Maintenance et mises à jour du site Web",
        "service_item_2": "Optimisation des performances",
        "service_item_3": "Surveillance de la sécurité",
        "service_item_4": "Sauvegarde et récupération",
        "sm_strategy": "Stratégie & Contenu",
        "sm_paid_ads": "Publicité Payante",
        "sm_community": "Croissance de la Communauté",
        "sm_analytics": "Analytique",
        "sem_google_ads": "Google Ads",
        "sem_display_ads": "Publicité Display",
        "sem_retargeting": "Reciblage",
        "sem_keyword_research": "Recherche de Mots-Clés",
        "web_design_custom": "Conception de Site Web Personnalisé",
        "web_design_ecommerce": "Solutions E-commerce",
        "web_design_seo": "Optimisation SEO",
        "web_design_maintenance": "Maintenance",
        "branding_strategy": "Stratégie de Marque",
        "branding_logo": "Conception de Logo",
        "branding_identity": "Identité Corporative",
        "branding_creatives": "Créations Marketing",
        "video_promotional": "Vidéos Promotionnelles",
        "video_reels": "Bobines de Réseaux Sociaux",
        "video_motion": "Motion Graphics",
        "video_animations": "Animations de Logo",
        "call_anytime_label": "Appelez à tout moment",
        "video_editing_menu": "Montage vidéo et graphisme animé",
        "blog_by": "Par",
        "blog_no_comments": "Aucun commentaire",
        "blog_latest_news": "Dernières Nouvelles",
        "blog_cat_ai_content": "Contenu IA",
        "blog_cat_ai_tech": "Technologie IA",
        "blog_cat_ui_design": "Design UI",
        "footer_web_design": "Conception Web",
        "contact_send_email": "Envoyer un e-mail",
        "contact_location": "Nairobi, Kenya",
        "blog_title_web_dev": "Les essentiels du developpement Web pour chaque entreprise",
        "blog_title_ai_web": "Comment l'IA revolutionne le developpement Web",
        "blog_title_hashtag": "Strategies de hashtag efficaces pour augmenter la portee"
    },
    "de": {
        "nav_home": "Startseite",
        "nav_services": "Dienstleistungen",
        "nav_blog": "Blog",
        "nav_about": "Über uns",
        "nav_contact": "Kontakt",
        "nav_projects": "Projekte",
        "nav_faq": "FAQ",
        "menu_all_services": "Alle Dienstleistungen",
        "menu_social_media_marketing": "Social Media Marketing",
        "menu_web_design_development": "Webdesign und Entwicklung",
        "menu_branding_graphics_design": "Branding und Grafikdesign",
        "menu_printing_brand_production": "Druck und Markenproduktion",
        "header_call_anytime": "Jederzeit anrufen",
        "footer_copyright": "© Urheberrecht 2026 von Anasi Marketing",
        "service_web_design": "Webdesign (UI/UX)",
        "service_corp_web": "Unternehmens-/Portfolio-Websites",
        "service_maint": "Wartung & Support",
        "service_branding": "Branding & Kreativdesign",
        "btn_get_started": "Kostenlos starten",
        "search_placeholder": "Suchen...",
        "about_title": "Über unsere Firma",
        "about_heading": "Wir liefern innovative Ideen, um Ihre Digitalagentur zu stärken.",
        "about_text": "Wir sind eine ergebnisorientierte Digitalmarketing- und Kreativagentur.",
        "services_title": "Unsere Dienstleistungen",
        "services_heading": "Stärken Sie Ihr Unternehmen mit<br>innovativen digitalen Dienstleistungen",
        "blog_heading": "Neueste Nachrichten & Artikel",
        "banner_sub_title": "Wir schaffen leistungsstarke digitale Erlebnisse",
        "banner_title": "Wir vermarkten Marken nicht nur — wir positionieren sie.",
        "banner_text": "Wir sind eine erstklassige Full-Service-Digitalmarketing- und Kreativagentur.",
        "btn_custom_quote": "Fordern Sie ein individuelles Angebot an",
        "banner_info_text": "Werten Sie Ihre Marke heute auf",
        "service_social_media": "Social Media<br>Marketing",
        "service_sem": "Suchmaschinenmarketing",
        "service_video_editing": "Videobearbeitung & Motion Graphics",
        "btn_more": "Mehr",
        "about_exp_text": "Erleben Sie hochwertige Digitalmarketing-Dienstleistungen",
        "btn_discover_more": "MEHR ENTDECKEN",
        "why_choose_us": "Warum uns wählen",
        "leading_company_title": "Anerkannt als eines der führenden Unternehmen!",
        "contact_us_title": "Kontaktieren Sie uns",
        "get_in_touch_title": "Kontakt aufnehmen",
        "form_name": "Ihr Name",
        "form_email": "E-Mail-Adresse",
        "form_subject": "Betreff eingeben",
        "form_phone": "Telefon eingeben",
        "form_message": "Nachricht schreiben",
        "btn_send_message": "Nachricht senden",
        "from_the_blog": "Aus dem Blog",
        "news_articles_title": "Nachrichten & Artikel",
        "read_more": "Weiterlesen",
        "footer_about_text": "Wir sind eine ergebnisorientierte Digitalmarketing- und Kreativagentur.",
        "footer_quick_link": "Schnelllink",
        "footer_company": "Unternehmen",
        "footer_contact": "Kontakt",
        "how_it_works_title": "Wie es funktioniert",
        "how_it_works_heading": "Unser Ansatz ist es, zu kreieren",
        "how_it_works_step1": "Projektplanung",
        "how_it_works_step2": "Entwicklung",
        "how_it_works_step3": "Schneller Support",
        "footer_looking_for": "Suchen Sie professionelles digitales Marketing?",
        "service_item_1": "Webservice-Wartung & Updates",
        "service_item_2": "Leistungsoptimierung",
        "service_item_3": "Sicherheitsüberwachung",
        "service_item_4": "Sicherung & Wiederherstellung",
        "sm_strategy": "Strategie & Inhalte",
        "sm_paid_ads": "Bezahlte Werbung",
        "sm_community": "Gemeinschaftswachstum",
        "sm_analytics": "Analytik",
        "sem_google_ads": "Google Ads",
        "sem_display_ads": "Display-Werbung",
        "sem_retargeting": "Retargeting",
        "sem_keyword_research": "Stichwortforschung",
        "web_design_custom": "Benutzerdefiniertes Webdesign",
        "web_design_ecommerce": "E-Commerce-Lösungen",
        "web_design_seo": "SEO-Optimierung",
        "web_design_maintenance": "Wartung",
        "branding_strategy": "Markenstrategie",
        "branding_logo": "Logo-Design",
        "branding_identity": "Unternehmensidentität",
        "branding_creatives": "Marketing-Kreationen",
        "video_promotional": "Werbevideos",
        "video_reels": "Social-Media-Reels",
        "video_motion": "Motion Graphics",
        "video_animations": "Logo-Animationen",
        "call_anytime_label": "Jederzeit anrufen",
        "video_editing_menu": "Videobearbeitung & Motion Graphics",
        "blog_by": "Von",
        "blog_no_comments": "Keine Kommentare",
        "blog_latest_news": "Neueste Nachrichten",
        "blog_cat_ai_content": "KI-Inhalte",
        "blog_cat_ai_tech": "KI-Technologie",
        "blog_cat_ui_design": "UI-Design",
        "footer_web_design": "Webdesign",
        "contact_send_email": "E-Mail senden",
        "contact_location": "Nairobi, Kenia",
        "blog_title_web_dev": "Grundlagen der Webentwicklung fur jedes Unternehmen",
        "blog_title_ai_web": "Wie KI die Webentwicklung revolutioniert",
        "blog_title_hashtag": "Wirksame Hashtag-Strategien zur Erhohung der Reichweite"
    },
    "it": {
        "nav_home": "Home",
        "nav_services": "Servizi",
        "nav_blog": "Blog",
        "nav_about": "Chi siamo",
        "nav_contact": "Contatto",
        "nav_projects": "Progetti",
        "nav_faq": "FAQ",
        "menu_all_services": "Tutti i servizi",
        "menu_social_media_marketing": "Marketing sui social media",
        "menu_web_design_development": "Web design e sviluppo",
        "menu_branding_graphics_design": "Branding e design grafico",
        "menu_printing_brand_production": "Stampa e produzione del brand",
        "header_call_anytime": "Chiama in qualsiasi momento",
        "footer_copyright": "© Diritto d'autore 2026 di Anasi Marketing",
        "service_web_design": "Progettazione siti web (UI/UX)",
        "service_corp_web": "Siti web aziendali/Portfolio",
        "service_maint": "Manutenzione e supporto",
        "service_branding": "Branding e design creativo",
        "btn_get_started": "Inizia gratuitamente",
        "search_placeholder": "Cerca...",
        "about_title": "Sulla nostra azienda",
        "about_heading": "Forniamo idee innovative per elevare la tua agenzia digitale.",
        "about_text": "Siamo un'agenzia di marketing digitale e creativa orientata ai risultati.",
        "services_title": "I nostri servizi",
        "services_heading": "Potenzia il tuo business con<br>servizi digitali innovativi",
        "blog_heading": "Ultime notizie e articoli",
        "banner_sub_title": "Creiamo potenti esperienze digitali",
        "banner_title": "Non ci limitiamo a commercializzare i marchi, li posizioniamo.",
        "banner_text": "Siamo un'agenzia di marketing digitale e creativa premium.",
        "btn_custom_quote": "Richiedi un preventivo personalizzato",
        "banner_info_text": "Elevate il vostro marchio oggi stesso",
        "service_social_media": "Marketing sui<br>social<br>media",
        "service_sem": "Marketing sui motori di ricerca",
        "service_video_editing": "Montaggio video e motion graphics",
        "btn_more": "Di più",
        "about_exp_text": "Scopri servizi di marketing digitale di qualità",
        "btn_discover_more": "SCOPRI DI PIÙ",
        "why_choose_us": "Perché sceglierci",
        "leading_company_title": "Riconosciuta come una delle aziende leader!",
        "contact_us_title": "Contattaci",
        "get_in_touch_title": "Entra in contatto",
        "form_name": "Il vostro nome",
        "form_email": "Indirizzo e-mail",
        "form_subject": "Inserisci l'oggetto",
        "form_phone": "Inserisci il numero di telefono",
        "form_message": "Scrivere un messaggio",
        "btn_send_message": "Invia un messaggio",
        "from_the_blog": "Dal Blog",
        "news_articles_title": "Notizie e articoli",
        "read_more": "Leggi di più",
        "footer_about_text": "Siamo un'agenzia di marketing digitale e creativa orientata ai risultati.",
        "footer_quick_link": "Link rapido",
        "footer_company": "Azienda",
        "footer_contact": "Contatto",
        "how_it_works_title": "Come funziona",
        "how_it_works_heading": "Il nostro approccio è creare",
        "how_it_works_step1": "Pianificazione del progetto",
        "how_it_works_step2": "Sviluppo",
        "how_it_works_step3": "Supporto rapido",
        "footer_looking_for": "Alla ricerca di un marketing digitale professionale?",
        "service_item_1": "Manutenzione e aggiornamenti del sito web",
        "service_item_2": "Ottimizzazione delle prestazioni",
        "service_item_3": "Monitoraggio della sicurezza",
        "service_item_4": "Backup e ripristino",
        "sm_strategy": "Strategia e Contenuti",
        "sm_paid_ads": "Pubblicità A Pagamento",
        "sm_community": "Crescita della Comunità",
        "sm_analytics": "Analitiche",
        "sem_google_ads": "Google Ads",
        "sem_display_ads": "Pubblicità Display",
        "sem_retargeting": "Retargeting",
        "sem_keyword_research": "Ricerca di Parole Chiave",
        "web_design_custom": "Progettazione di Siti Web Personalizzati",
        "web_design_ecommerce": "Soluzioni E-commerce",
        "web_design_seo": "Ottimizzazione SEO",
        "web_design_maintenance": "Manutenzione",
        "branding_strategy": "Strategia di marca",
        "branding_logo": "Progettazione logo",
        "branding_identity": "Identità aziendale",
        "branding_creatives": "Creatività di Marketing",
        "video_promotional": "Video Promozionali",
        "video_reels": "Bobine dei Social Media",
        "video_motion": "Motion Graphics",
        "video_animations": "Animazioni Logo",
        "call_anytime_label": "Chiama in qualsiasi momento",
        "video_editing_menu": "Montaggio video e motion graphics",
        "blog_by": "Di",
        "blog_no_comments": "Nessun commento",
        "blog_latest_news": "Ultime notizie",
        "blog_cat_ai_content": "Contenuto AI",
        "blog_cat_ai_tech": "Tecnologia AI",
        "blog_cat_ui_design": "Design UI",
        "footer_web_design": "Web design",
        "contact_send_email": "Invia email",
        "contact_location": "Nairobi, Kenya",
        "blog_title_web_dev": "Le basi dello sviluppo Web per ogni azienda",
        "blog_title_ai_web": "Come l'IA sta rivoluzionando lo sviluppo Web",
        "blog_title_hashtag": "Strategie efficaci di hashtag per aumentare la portata"
    },
    "pt": {
        "nav_home": "Início",
        "nav_services": "Serviços",
        "nav_blog": "Blog",
        "nav_about": "Sobre nós",
        "nav_contact": "Contato",
        "nav_projects": "Projetos",
        "nav_faq": "FAQ",
        "menu_all_services": "Todos os serviços",
        "menu_social_media_marketing": "Marketing de mídia social",
        "menu_web_design_development": "Web design e desenvolvimento",
        "menu_branding_graphics_design": "Branding e design gráfico",
        "menu_printing_brand_production": "Impressão e produção de marca",
        "header_call_anytime": "Ligue a qualquer hora",
        "footer_copyright": "© Direitos autorais 2026 pela Anasi Marketing",
        "service_web_design": "Web Design (UI/UX)",
        "service_corp_web": "Sites corporativos/Portfólio",
        "service_maint": "Manutenção e Suporte",
        "service_branding": "Marca e Design Criativo",
        "btn_get_started": "Comece gratuitamente",
        "search_placeholder": "Procurar...",
        "about_title": "Sobre nossa empresa",
        "about_heading": "Entregamos ideias inovadoras para elevar sua agência digital.",
        "about_text": "Somos uma agência de marketing digital e criação focada em resultados.",
        "services_title": "Nossos Serviços",
        "services_heading": "Capacite seu negócio com<br>serviços digitais inovadores",
        "blog_heading": "Últimas notícias e artigos",
        "banner_sub_title": "Criamos experiências digitais poderosas",
        "banner_title": "Não comercializamos apenas marcas — nós as posicionamos.",
        "banner_text": "Somos uma agência de marketing digital e criação de serviço completo.",
        "btn_custom_quote": "Solicite um orçamento personalizado",
        "banner_info_text": "Eleve sua marca hoje",
        "service_social_media": "Marketing de<br>Mídia<br>Social",
        "service_sem": "Marketing de Busca (SEM)",
        "service_video_editing": "Edição de Vídeo e Motion Graphics",
        "btn_more": "Mais",
        "about_exp_text": "Experimente serviços de marketing digital de qualidade",
        "btn_discover_more": "DESCUBRA MAIS",
        "why_choose_us": "Por que nos escolher",
        "leading_company_title": "Reconhecida como uma das empresas líderes!",
        "contact_us_title": "Contate-nos",
        "get_in_touch_title": "Entre em contato",
        "form_name": "Seu nome",
        "form_email": "Endereço de e-mail",
        "form_subject": "Insira o assunto",
        "form_phone": "Insira o telefone",
        "form_message": "Escreva uma mensagem",
        "btn_send_message": "Enviar uma mensagem",
        "from_the_blog": "Do Blog",
        "news_articles_title": "Notícias e artigos",
        "read_more": "Leia mais",
        "footer_about_text": "Somos uma agência de marketing digital e criação focada em resultados.",
        "footer_quick_link": "Link rápido",
        "footer_company": "Empresa",
        "footer_contact": "Contato",
        "how_it_works_title": "Como funciona",
        "how_it_works_heading": "Nossa abordagem é criar",
        "how_it_works_step1": "Planejamento de projeto",
        "how_it_works_step2": "Desenvolvimento",
        "how_it_works_step3": "Suporte rápido",
        "footer_looking_for": "Procurando por Marketing Digital Profissional?",
        "service_item_1": "Manutenção e atualizações do site",
        "service_item_2": "Otimização de performance",
        "service_item_3": "Monitoramento de segurança",
        "service_item_4": "Backup e recuperação",
        "sm_strategy": "Estratégia e Conteúdo",
        "sm_paid_ads": "Publicidade Paga",
        "sm_community": "Crescimento da Comunidade",
        "sm_analytics": "Análise",
        "sem_google_ads": "Google Ads",
        "sem_display_ads": "Publicidade Display",
        "sem_retargeting": "Retargeting",
        "sem_keyword_research": "Pesquisa de Palavras-chave",
        "web_design_custom": "Design de Site Personalizado",
        "web_design_ecommerce": "Soluções E-commerce",
        "web_design_seo": "Otimização SEO",
        "web_design_maintenance": "Manutenção",
        "branding_strategy": "Estratégia de Marca",
        "branding_logo": "Design de Logo",
        "branding_identity": "Identidade Corporativa",
        "branding_creatives": "Criativos de Marketing",
        "video_promotional": "Vídeos Promocionais",
        "video_reels": "Bobinas de Mídias Sociais",
        "video_motion": "Motion Graphics",
        "video_animations": "Animações de Logo",
        "call_anytime_label": "Ligue a qualquer hora",
        "video_editing_menu": "Edição de Vídeo e Motion Graphics",
        "blog_by": "Por",
        "blog_no_comments": "Sem comentários",
        "blog_latest_news": "Últimas Notícias",
        "blog_cat_ai_content": "Conteúdo de IA",
        "blog_cat_ai_tech": "Tecnologia de IA",
        "blog_cat_ui_design": "Design de IU",
        "footer_web_design": "Web design",
        "contact_send_email": "Enviar email",
        "contact_location": "Nairobi, Quenia",
        "blog_title_web_dev": "Essenciais de desenvolvimento Web para todo negocio",
        "blog_title_ai_web": "Como a IA esta revolucionando o desenvolvimento Web",
        "blog_title_hashtag": "Estrategias eficazes de hashtag para aumentar o alcance"
    },
    "es": {
        "nav_home": "Inicio",
        "nav_services": "Servicios",
        "nav_blog": "Blog",
        "nav_about": "Sobre nosotros",
        "nav_contact": "Contacto",
        "nav_projects": "Proyectos",
        "nav_faq": "FAQ",
        "menu_all_services": "Todos los servicios",
        "menu_social_media_marketing": "Marketing en redes sociales",
        "menu_web_design_development": "Diseño y desarrollo web",
        "menu_branding_graphics_design": "Branding y diseño gráfico",
        "menu_printing_brand_production": "Impresión y producción de marca",
        "header_call_anytime": "Llamar en cualquier momento",
        "footer_copyright": "© Derechos de autor 2026 por Anasi Marketing",
        "service_web_design": "Diseño Web (UI/UX)",
        "service_corp_web": "Sitios web corporativos/Portafolio",
        "service_maint": "Mantenimiento y soporte",
        "service_branding": "Branding y diseño creativo",
        "btn_get_started": "Empiece gratis",
        "search_placeholder": "Buscar...",
        "about_title": "Sobre nuestra compañía",
        "about_heading": "Entregamos ideas innovadoras para elevar su agencia digital.",
        "about_text": "Somos una agencia de marketing digital y creativa impulsada por resultados.",
        "services_title": "Nuestros Servicios",
        "services_heading": "Potencie su negocio con<br>servicios digitales innovadores",
        "blog_heading": "Últimas noticias y artículos",
        "banner_sub_title": "Creamos experiencias digitales potentes",
        "banner_title": "No solo comercializamos marcas, las posicionamos.",
        "banner_text": "Somos una agencia creativa y de marketing digital de servicio completo.",
        "btn_custom_quote": "Solicite una cotización personalizada",
        "banner_info_text": "Eleve su marca hoy mismo",
        "service_social_media": "Marketing en<br>redes<br>sociales",
        "service_sem": "Marketing en buscadores (SEM)",
        "service_video_editing": "Edición de vídeo y motion graphics",
        "btn_more": "Más",
        "about_exp_text": "Más de 50 años de experiencia en servicios",
        "btn_discover_more": "DESCUBRIR MÁS",
        "why_choose_us": "Por qué elegirnos",
        "leading_company_title": "¡Reconocida como una de las empresas líderes!",
        "contact_us_title": "Contáctenos",
        "get_in_touch_title": "Ponerse en contacto",
        "form_name": "Su nombre",
        "form_email": "Correo electrónico",
        "form_subject": "Ingrese el asunto",
        "form_phone": "Ingrese el teléfono",
        "form_message": "Escribir un mensaje",
        "btn_send_message": "Enviar un mensaje",
        "from_the_blog": "Del blog",
        "news_articles_title": "Noticias y artículos",
        "read_more": "Leer más",
        "footer_about_text": "Somos una agencia de marketing digital y creativa impulsada por resultados.",
        "footer_quick_link": "Enlace rápido",
        "footer_company": "Compañía",
        "footer_contact": "Contacto",
        "how_it_works_title": "Cómo funciona",
        "how_it_works_heading": "Nuestro enfoque es crear",
        "how_it_works_step1": "Planificación del proyecto",
        "how_it_works_step2": "Desarrollo",
        "how_it_works_step3": "Soporte rápido",
        "footer_looking_for": "¿Busca marketing digital profesional?",
        "service_item_1": "Mantenimiento y actualizaciones del sitio web",
        "service_item_2": "Optimización del rendimiento",
        "service_item_3": "Monitoreo de seguridad",
        "service_item_4": "Copia de seguridad y recuperación",
        "sm_strategy": "Estrategia y Contenido",
        "sm_paid_ads": "Publicidad Pagada",
        "sm_community": "Crecimiento de la Comunidad",
        "sm_analytics": "Análisis",
        "sem_google_ads": "Google Ads",
        "sem_display_ads": "Publicidad Display",
        "sem_retargeting": "Retargeting",
        "sem_keyword_research": "Investigación de Palabras Clave",
        "web_design_custom": "Diseño de Sitio Web Personalizado",
        "web_design_ecommerce": "Soluciones de Comercio Electrónico",
        "web_design_seo": "Optimización SEO",
        "web_design_maintenance": "Mantenimiento",
        "branding_strategy": "Estrategia de Marca",
        "branding_logo": "Diseño de Logo",
        "branding_identity": "Identidad Corporativa",
        "branding_creatives": "Creatividad de Marketing",
        "video_promotional": "Videos Promocionales",
        "video_reels": "Carrete de Redes Sociales",
        "video_motion": "Motion Graphics",
        "video_animations": "Animaciones de Logo",
        "call_anytime_label": "Llámanos en cualquier momento",
        "video_editing_menu": "Edición de Video y Motion Graphics",
        "blog_by": "Por",
        "blog_no_comments": "Sin comentarios",
        "blog_latest_news": "Últimas Noticias",
        "blog_cat_ai_content": "Contenido de IA",
        "blog_cat_ai_tech": "Tecnología de IA",
        "blog_cat_ui_design": "Diseño de IU",
        "footer_web_design": "Diseño web",
        "contact_send_email": "Enviar correo",
        "contact_location": "Nairobi, Kenia",
        "blog_title_web_dev": "Aspectos esenciales del desarrollo web para cada negocio",
        "blog_title_ai_web": "Como la IA esta revolucionando el desarrollo web",
        "blog_title_hashtag": "Estrategias de hashtag efectivas para aumentar el alcance"
    }
};

function updatePageLanguage(lang) {
    const elements = document.querySelectorAll('[data-i18n]');

    elements.forEach(element => {
        const key = element.getAttribute('data-i18n');
        if (siteTranslations[lang] && siteTranslations[lang][key]) {
            // Check if it's an input with placeholder
            if (element.tagName === 'INPUT' && element.hasAttribute('placeholder')) {
                element.placeholder = siteTranslations[lang][key];
            } else if (element.tagName === 'TEXTAREA') {
                element.placeholder = siteTranslations[lang][key];
            } else {
                // Use innerHTML to preserve HTML tags like <br>
                element.innerHTML = siteTranslations[lang][key];
            }
        }
    });

    // Save preference
    localStorage.setItem('selected_language', lang);

    // Update switcher values if multiple exist
    const switchers = document.querySelectorAll('.custom-lang-switcher');
    switchers.forEach(s => s.value = lang);
}

document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('selected_language');
    const supportedLangs = Object.keys(siteTranslations);

    const resolveBrowserLanguage = () => {
        const browserLocale = (navigator.language || '').toLowerCase();
        const primary = browserLocale.split('-')[0];

        if (supportedLangs.includes(browserLocale)) {
            return browserLocale;
        }

        if (supportedLangs.includes(primary)) {
            return primary;
        }

        return 'en';
    };

    const initialLang = savedLang || resolveBrowserLanguage();

    // Initialize switchers
    const switchers = document.querySelectorAll('.custom-lang-switcher');
    switchers.forEach(select => {
        select.value = initialLang;
        select.addEventListener('change', (e) => {
            updatePageLanguage(e.target.value);
        });
    });

    // Initial update
    updatePageLanguage(initialLang);
});
